import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Typewriter from 'typewriter-effect';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Martin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/b46125b132.js" crossorigin="anonymous"></script>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          hi, I'm Martin
        </h1>
        {/* <Typewriter
        options={{
          strings: ["hi, i'm Martin :D"],
          autoStart: true
        }}
        /> */}
        <Typewriter
          onInit={(typewriter) => {
            typewriter.typeString('Hello World!')
              .callFunction(() => {
                console.log('String typed out!');
              })
              .start();
          }}
          style = {{color: "red"}}
        />

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>testing 123</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>lmaooooo &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/AstraI24"
          target="_blank"
          rel="noopener noreferrer"
        >
          <i class="fa-brands fa-github fa-2xl"></i>
          
        </a>
        
        <a
          href="https://github.com/AstraI24"
          target="_blank"
          rel="noopener noreferrer"
        >
          <i class="fa-brands fa-linkedin-in fa-2xl"></i>
          
        </a>

        <a
          href="https://github.com/AstraI24"
          target="_blank"
          rel="noopener noreferrer"
        >
          <i class="fa-brands fa-instagram fa-2xl"></i>
          
        </a>
        
      </footer>
    </div>
  )
}
